"""agrega tabla sync_logs

Revision ID: ac39f9d9b2c2
Revises: 83844ed514f6
Create Date: 2026-06-30 08:28:56.063637
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac39f9d9b2c2'
down_revision: Union[str, None] = '83844ed514f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('teams', sa.Integer(), nullable=True),
    sa.Column('players', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_logs_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_logs_status'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_id'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_finished_at'))

    op.drop_table('sync_logs')
    # ### end Alembic commands ###
