"""esquema inicial liga mx

Revision ID: 83844ed514f6
Revises: 
Create Date: 2026-06-30 07:57:33.600014
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83844ed514f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_link'), ['link'], unique=True)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tournament_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasons_name'), ['name'], unique=False)

    op.create_table('stadiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stadiums_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stadiums_name'), ['name'], unique=False)

    op.create_table('top_scorers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('top_scorers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_top_scorers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_top_scorers_player'), ['player'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)

    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weeks_id'), ['id'], unique=False)

    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('possession', sa.Float(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_stats_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_stats_id'), ['id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sofascore_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_sofascore_event_id'), ['sofascore_event_id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)

    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=True),
    sa.Column('won', sa.Integer(), nullable=True),
    sa.Column('drawn', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('goal_difference', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standings_id'), ['id'], unique=False)

    op.create_table('match_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('sofascore_event_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_time', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_home', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_events_id'), ['id'], unique=False)

    op.create_table('match_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('sofascore_event_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('is_substitute', sa.Integer(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_lineups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_lineups_id'), ['id'], unique=False)

    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_stats_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_stats_player_name'), ['player_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_stats_player_name'))
        batch_op.drop_index(batch_op.f('ix_player_stats_id'))

    op.drop_table('player_stats')
    with op.batch_alter_table('match_lineups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_lineups_id'))

    op.drop_table('match_lineups')
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_events_id'))

    op.drop_table('match_events')
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standings_id'))

    op.drop_table('standings')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_id'))

    op.drop_table('players')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_sofascore_event_id'))
        batch_op.drop_index(batch_op.f('ix_matches_id'))

    op.drop_table('matches')
    with op.batch_alter_table('match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_stats_id'))
        batch_op.drop_index(batch_op.f('ix_match_stats_event_id'))

    op.drop_table('match_stats')
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weeks_id'))

    op.drop_table('weeks')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_id'))

    op.drop_table('teams')
    with op.batch_alter_table('top_scorers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_top_scorers_player'))
        batch_op.drop_index(batch_op.f('ix_top_scorers_id'))

    op.drop_table('top_scorers')
    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stadiums_name'))
        batch_op.drop_index(batch_op.f('ix_stadiums_id'))

    op.drop_table('stadiums')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_name'))
        batch_op.drop_index(batch_op.f('ix_seasons_id'))

    op.drop_table('seasons')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_link'))
        batch_op.drop_index(batch_op.f('ix_news_id'))

    op.drop_table('news')
    # ### end Alembic commands ###
