"""agrega external_event_id a matches

Revision ID: 806ef25d4654
Revises: ac39f9d9b2c2
Create Date: 2026-06-30 08:48:46.292060
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806ef25d4654'
down_revision: Union[str, None] = 'ac39f9d9b2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_event_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_matches_external_event_id'), ['external_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_external_event_id'))
        batch_op.drop_column('external_event_id')

    # ### end Alembic commands ###
